name: ci
on:
  pull_request:
  push:
    branches:
      - master
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: current
      - name: Install dependencies
        run: |
          npm ci
      - name: Ensure build succeeds
        run: |
          npm run build
      - name: Report Biome output to GitHub
        run: |
          npx biome ci --reporter=github
        continue-on-error: true
      - name: Run tests
        run: |
          npm run test
